accessControl:
  userfile: /octoprint/octoprint/users.yaml
server:
  commands:
    serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream
serial:
  additionalPorts:
  - /dev/octoprinter
